### ISSUE TITLE
Data protection officer directive?

### ISSUE THREAD

**Issue by jpgoldberg** [securitytxt/security-txt#106]
There are growing conventions and regulatory requirements to list contact information for a data protection officer.

I am uncertain as to whether that

1.  Should be a different document, e.g., `/.well-known/data-protection.txt`, _or_
2. Something to include as "current" in this draft, _or_
2. Something to register later.

But I did want to mention the anticipated need for something like this.

**Comment by nightwatchcyber** [comment]
I would think that would be something that companies would include in their privacy policies, I am not sure if this would fall within the scope of this project which is focused on security.

I am also wondering if a standard email address like "privacy@example.com" may be a good first step instead. The reason why "security@example.com" doesn't work well is because there are additional requirements like best way to communicate, encryption keys to use, etc. that are needed.

**Comment by jpgoldberg** [comment]
Thanks @nightwatchcyber. That all makes sense. Perhaps someday there will be a standard or at least conventional email address for this. That would, indeed, be the sensible approach and no need to use /.well-known

**Comment by nightwatchcyber** [comment]
@jpgoldberg -  I ended up writing a small Internet draft to address this:
https://github.com/nightwatchcybersecurity/privacy-mailbox
https://tools.ietf.org/html/draft-shafranovich-privacy-mailbox-00
