### ISSUE TITLE
Specify allowed characters in comments

### ISSUE THREAD

**Issue by joker314** [securitytxt/security-txt#123]
In the ABNF portion, we learn that comments can only contain certain unprintable characters. The null character, the bell character, the form-feed character, etc. are not allowed.

Should we be specifying this in *3.1 Comments*?

**Comment by joker314** [comment]
This is for https://securitytxt.io/#rfc.section.5

**Comment by nightwatchcyber** [comment]
Will add to section 3.1 - all ASCII printable + all of Unicode

**Comment by nightwatchcyber** [comment]
@bortzmeyer - can you comment on this? I am having trouble finding a good existing RFC that does something similar. Closest thing I can see is RFC 3261 or this draft: https://tools.ietf.org/html/draft-seantek-unicode-in-abnf-03.

We would redefine comments from:
> `comment                = "#" *(WSP / VCHAR / %xA0-E007F)`

To:
> `comment                = "#" *(WSP / VCHAR / %x20-FF) ; May include Unicode encoded data as per RFC5198 `

**Comment by joker314** [comment]
Is there a problem with current version of the ABNF?

**Comment by bortzmeyer** [comment]
> `comment                = "#" *(WSP / VCHAR / %x20-FF) ; May include Unicode encoded data as per RFC5198 `

I don't see why we should change the ABNF. Your proposed change *removes* Unicode characters and then add a comment saying they are authorized. I'm confused.

May be the confusion comes from the fact that many people believe RFC 5234 describes bytes. But it actually describes characters. See its section 2.4. So, I think the previous version is better (%xA0-E007F)

**Comment by nightwatchcyber** [comment]
@bortzmeyer - I think I was inaccurate with the ABNF here. The issue the original reporter raised is that "%xA0-E007F" includes ASCII control characters, and doesn't include all of Unicode. I was trying to narrow it to start at ASCII 32 (%x20) and make it go until the end of the Unicode range. It is the end that I am having trouble with - I believe the highest character is U+10FFFF. That means it would like this:

> `comment = "#" *(WSP / VCHAR / %x20-0FFFF)`

**Comment by nightwatchcyber** [comment]
> Is there a problem with current version of the ABNF?

It includes control characters and doesn't go to the end of the Unicode ranges

**Comment by knightpfhor** [comment]
It would probably be a good idea to include x9, xA and xD (tab, carriage return, line feed) as valid characters too.

**Comment by joker314** [comment]
@knightpfhor I don't think the carriage return or line feeds should be valid characters inside a comment, because comments/directives are terminated by those characters, so if you could use newlines you wouldn't know where the comment ends.

I think your idea about tabs is good though.

**Comment by tomnomnom** [comment]
Just sticking my nose in briefly to clear a couple of things up...

Tabs are included as part of `WSP`, and `VCHAR` includes `%x21-7E`

E.g. comments in RFC 5234 are defined as:

```
";" *(WSP / VCHAR) CRLF
```

The original requirement was only that people are able to write comments in languages that require the use of characters outside of the `VCHAR` range.

**Comment by nightwatchcyber** [comment]
As per @tomnomnom, the following is in the draft now:
> comment  = "#" *(WSP / VCHAR / %xA0-E007F)

WSP and VCHAR definitions from [RFC 5343](https://tools.ietf.org/html/rfc5234) include:
> HTAB =  %x09
> SP =  %x20
> VCHAR  =  %x21-7E

Newlines are specifically excluded since the ABNF grammar that defines the security.txt file itself reserves that as a separator between lines so comments would have to be written with multiple lines starting with "#".

So this covers ASCII 09 (TAB), and everything from 32 to 126 / %x21-7E (except for DEL which is 127 / %x7F). The question is cover everything above that so we can include Unicode. Right now that starts with %xA0 / 160 which skips a bunch of letters, and goes up to %xE007F which is the end of the tags Unicode range and right before a bunch of unused and supplementary ranges (see ranges [here).](https://en.wikipedia.org/wiki/Unicode_block)

The original request is to spell all of this out in section 3.1 so a casual reader can see it without trying to parse the ABNF. However, while looking at that, I was also wondering if we can just go to the end of the Unicode range. So the proposed ABNF is simply this:
> comment  = "#" *(WSP / VCHAR / %x80-FFFFF)

This would include ASCII 9 (TAB), everything from ASCII 32 (SPACE) until 126, skip the delete character, and then include everything from ASCII 128 until the end of Unicode including all private and unused ranges (FFFFF).

**Comment by nightwatchcyber** [comment]
> As per @tomnomnom, the following is in the draft now:
> 
> > comment  = "#" *(WSP / VCHAR / %xA0-E007F)
> 
> WSP and VCHAR definitions from [RFC 5343](https://tools.ietf.org/html/rfc5234) include:
> 
> > HTAB =  %x09
> > SP =  %x20
> > VCHAR  =  %x21-7E
> 
> Newlines are specifically excluded since the ABNF grammar that defines the security.txt file itself reserves that as a separator between lines so comments would have to be written with multiple lines starting with "#".
> 
> So this covers ASCII 09 (TAB), and everything from 32 to 126 / %x21-7E (except for DEL which is 127 / %x7F). The question is cover everything above that so we can include Unicode. Right now that starts with %xA0 / 160 which skips a bunch of letters, and goes up to %xE007F which is the end of the tags Unicode range and right before a bunch of unused and supplementary ranges (see ranges [here).](https://en.wikipedia.org/wiki/Unicode_block)
> 
> The original request is to spell all of this out in section 3.1 so a casual reader can see it without trying to parse the ABNF. However, while looking at that, I was also wondering if we can just go to the end of the Unicode range. So the proposed ABNF is simply this:
> 
> > comment  = "#" *(WSP / VCHAR / %x80-FFFFF)
> 
> This would include ASCII 9 (TAB), everything from ASCII 32 (SPACE) until 126, skip the delete character, and then include everything from ASCII 128 until the end of Unicode including all private and unused ranges (FFFFF).

I added a pull request illustrating my example

**Comment by nightwatchcyber** [comment]
Done in -05
