### ISSUE TITLE
Consider mandating encryption when "mailto" is used in the "Contact" field

### ISSUE THREAD

**Issue by nightwatchcyber** [securitytxt/security-txt#134]
As per [this post:](https://www.ietf.org/mail-archive/web/saag/current/msg08452.html)

> I would additionally propose that, where the 'Contact:' directive is used to specify an email address using the 'mailto:' syntax, then it is necessary to also specify an encryption public key (via the 'Encryption:' directive) for protection of email messages sent to that contact address. So Section 3.4.3 should specify that the Encryption: directive MUST be used when the content of the Contact: directive is an email address. The specification cannot mandate that security researchers use encryption on email sent to this address - that would be out of scope - but an encryption key must at least be available. In practice this will mean a PGP public key is published on the web server or a separate key server, but security.txt should not mandate the format or the contents of the public key file.

**Comment by davidmays** [comment]
It strikes me as a bit heavy-handed and potentially non-inclusive to make this a MUST rather than a SHOULD. If the company posting the security-txt file is for some reason prohibited from using encryption, but still wants disclosure contacts made via email, I think the specification 1) Cannot stop them and 2) should not try. 

Attempting to interfere with the company's legal obligations or restrictions will likely cause them to create a non-compliant security-txt. 

Will a non-compliant security-txt cause problems for mechanical crawlers/parsers that are looking for them?

**Comment by nightwatchcyber** [comment]
Will try to address as part of #112

**Comment by nightwatchcyber** [comment]
Current draft reads (section 3.5.3):

> When the value of this directive is an email address, it is RECOMMENDED that encryption be used (as per Section 3.5.4).
