### ISSUE TITLE
Review my security.txt

### ISSUE THREAD

**Issue by k0nsl** [securitytxt/security-txt#211]
I just recently learned about this project and immediately found it to be a good idea.

I made a modest `security.txt` which I hope is enough. At any rate, would anyone involved be able to review it and tell me if I am missing anything important?

Link: [https://rodoh.info/security.txt](https://rodoh.info/security.txt)

Thanks in advance.

Faithfully,
-k0nsl

**Comment by k0nsl** [comment]
Should I add anything else which is essential or should I keep it lean like this?

Faithfully,
-k0nsl

**Comment by nightwatchcyber** [comment]
It looks ok but I would suggest looking at the parsers listed below and the generator on our website:
https://securitytxt.org/projects
https://securitytxt.org/

**Comment by MarcMogdanz** [comment]
The `Contact` field should contain the `mailto:` prefix if it's an e-mail address according to [3.5.3](https://datatracker.ietf.org/doc/html/draft-foudil-securitytxt-12#section-3.5.3), e.g. `Contact: mailto:security@example.com`.
And according to [3.5.5](https://datatracker.ietf.org/doc/html/draft-foudil-securitytxt-12#section-3.5.5) the `Expires` field should be in the ISO-8601 format and not required, but recommended: the date should not be more than one year in the future.

Otherwise it looks good.

**Comment by k0nsl** [comment]
Thank you @nightwatchcyber and @MarcMogdanz; I have made the suggested changes to my ´security.txt´ file and it is now correctly formatted.  👍

Faithfully,
-k0nsl
