### ISSUE TITLE
E-mail address in clear text is a bad idea

### ISSUE THREAD

**Issue by wimg** [securitytxt/security-txt#23]
I like all ideas that improve security and allow for easier coordination between security researchers, but adding a contact e-mail address in that file is a sure way to get bots to collect it, then start spamming for security tools.

A good system/network administrator shouldn't have any problems finding the right e-mail address through other, slightly harder-to-scrape ways.

Just my 2 cents...

**Comment by Plazmaz** [comment]
I will say that having contact information in a centralized place is extremely helpful when responding to larger scale issues. For instance, for contacting users who have open databases, this would drastically reduce the workload. While I can see the concern, I still feel that it would be useful to have it as an optional field.

**Comment by EdOverflow** [comment]
@wimg: The email value is an optional field. If you are worried about spam you can set a URI as the value and link to your security policy.

**Comment by davidmays** [comment]
Instead of an email, you could provide a URI to a contact form, and employ standard CAPTCHA techniques to prevent abuse of that form. 

Maybe all the form has is a text box to submit the researcher's email address and pgp pubkey, for the company to send an encrypted reply?

If a security researcher wants to have a discussion about a vuln, they should be more than comfortable submitting their own email contact information in exchange for a reply.

**Comment by austinheap** [comment]
Trying to protect e-mail addresses through obscurity isn't a winning approach. That said, and as @EdOverflow mentioned, if someone implementing `security.txt` for their site didn't want to include an e-mail in the `Contact` directive, they could simply point to a contact form, their HackerOne bounty program, etc.
