### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by hackerfactor** [securitytxt/security-txt#26]
I reviewed the draft for security.txt and the web site named "securitytxt.org" that generates security.txt files.  I think there are many serious issues.  These issues include:

1. The web site "securitytxt.org" generates files that do not follow the draft RFC.
Specifically: The draft RFC says that the 'Disclosure' field should be Full|Partial|None.  However, the web form for generating it says it should be a URL to the disclosure policy.

I prefer the URL, but that isn't what the draft RFC says.

2. The draft RFC has a lot of ambiguity.
For example, section 2.3 says that 'Contact:' must exist, but then lists different values that serve different purposes:
        Contact: security@example.com
        Contact: +1-201-555-0123
        Contact: https://example.com/security
This becomes a parsing nightmare. If it is going to do this, then it needs to standardize the types of content:
        Contact.email: security@example.com
        Contact.phone: +1-201-555-0123
        Contact.url: https://example.com/security

3. I can list multiple contact methods.  However, there is also no precedence listed for a preferred contact method.
The easy solution is to say that the precedence is in listed order. In the example, email is preferred, then phone, then URL.

4. I see room for exploitation as soon as someone builds a parser that harvests these security.txt files.
E.g., I can list 1 million Contact: lines and try to overflow the parser's buffer -- or at least consume all of their memory.
And there's no limit to the length of these fields.
And nothing stops me from adding in my own custom field, like a massive video (DVD-HD, of course) that shows how to submit a bug.

"It's not my fault you can't decode my security.txt file!  I'm following the standard!"

5. Location, location, location...
Nothing says it has to be at "/security.txt".
So I could be a big company with:
       https://bigcompany.com/security.txt
       https://bigcompany.com/product1/security.txt
       https://bigcompany.com/product2/security.txt
       https://bigcompany.com/product3/security.txt
       https://bigcompany.com/ads/security.txt
       https://bigcompany.com/personel/security.txt
       ...
Or maybe:
       https://bigcompany.com/security.txt
       https://bigcompany-cdn.com/security.txt
       https://security.bigcompany.com/security.txt
   Nothing says that these have to be the same file!

6. If people/bots start looking deeper into the directory structure, then I -- as a user who controls a subdirectory -- can hijack the vulnerability reporting process for a big company that gave me a free account.

7. The Draft RFC says every line must end with a "\n".
That becomes a problem when Windows users use \r\n.

8. I enjoy these english-only standards.
"Contact", "Encryption", "Disclosure"... yeah, foreign countries will love this.

9. Encryption is supposed to be for your PGP key.
But what if I want to use some other type of encryption?
Or what if someday PGP falls out of favor.  Then what?

10. There's no mention of existing standards that specify a security contact.
For example, RFC2142 says that there should be a security@ email address.

11. DNS hijacking is a very real problem. How can I validate that this security.txt file is legitimate?
Perhaps introduce a digital signature that can be validated via SSL, PGP, or DNS TXT record?  (Not SSL, PGP, or DNS used to access the file.)

Edit: Formatting, spelling.

**Comment by EdOverflow** [comment]
Thank you for taking the time to write up all these points.

> The web site "securitytxt.org" generates files that do not follow the draft RFC.
Specifically: The draft RFC says that the 'Disclosure' field should be Full|Partial|None. However, the web form for generating it says it should be a URL to the disclosure policy.

The `Disclosure:` directive has been removed from the new version of the draft that I plan on publishing today.

> I can list multiple contact methods. However, there is also no precedence listed for a preferred contact method.
The easy solution is to say that the precedence is in listed order. In the example, email is preferred, then phone, then URL.

When I discussed the Internet draft with the Google VRP team they said the exact same thing. This will be made clear in the new version of the draft.

> I see room for exploitation as soon as someone builds a parser that harvests these security.txt files.
E.g., I can list 1 million Contact: lines and try to overflow the parser's buffer -- or at least consume all of their memory.
And there's no limit to the length of these fields.
And nothing stops me from adding in my own custom field, like a massive video (DVD-HD, of course) that shows how to submit a bug.

What solution would you propose to this potential issue?

> Location, location, location...

The security.txt file is moving to the /.well-known/ path in the latest version of the draft. (#3)

> Nothing says it has to be at "/security.txt".

_"Security.txt is a text file located in the website's top-level directory."_ [[§ 2](https://tools.ietf.org/html/draft-foudil-securitytxt-00#section-2)]

> If people/bots start looking deeper into the directory structure, then I -- as a user who controls a subdirectory -- can hijack the vulnerability reporting process for a big company that gave me a free account.

See previous response above.

> The Draft RFC says every line must end with a "\n".
That becomes a problem when Windows users use \r\n.

This is an interesting point. I will have to give this more thought.

> I enjoy these english-only standards.
"Contact", "Encryption", "Disclosure"... yeah, foreign countries will love this.

In my opinion, this is not an issue otherwise we would all be coding in foreign languages by now.

> Encryption is supposed to be for your PGP key.
But what if I want to use some other type of encryption?
Or what if someday PGP falls out of favor. Then what?

While rereading [Section 2.4](https://tools.ietf.org/html/draft-foudil-securitytxt-00#section-2.4) I noticed that this part needs more work. I actually wanted to mention PGP as an example.

> There's no mention of existing standards that specify a security contact.
For example, RFC2142 says that there should be a security@ email address.

I am already aware of this issue. (https://github.com/EdOverflow/security-txt/issues/25)

> DNS hijacking is a very real problem. How can I validate that this security.txt file is legitimate?
Perhaps introduce a digital signature that can be validated via SSL, PGP, or DNS TXT record? (Not SSL, PGP, or DNS used to access the file.)

This point is still up for discussion in https://github.com/EdOverflow/security-txt/issues/19.

Once again, thank you very much for the constructive feedback.

**Comment by tomnomnom** [comment]
Hi, @hackerfactor. I helped out with the grammar and ABNF for the draft, so I'm fairly well placed to add some more insight around points 2 (`The draft RFC has a lot of ambiguity`) and 7 (`The Draft RFC says every line must end with a "\n".`) specifically.

## Parsing and contact fields 
> 2. The draft RFC has a lot of ambiguity.
For example, section 2.3 says that 'Contact:' must exist, but then lists different values that serve different purposes:
...
This becomes a parsing nightmare.

As part of writing the ABNF I wrote a couple of parsers to verify that everything was easy enough to parse, and writing them did cause us to make some changes to the grammar. Although I had similar concerns to you initially, I found parsing the contact fields to be of no real difficulty.

Parsing security.txt is, for the most part, is as simple as:

1. Split the file by `\n`
2. Trim remaining whitespace from the ends of the lines
3. Split each line by `:` with a max of 2 returned items
4. Verify that the left side of the `:` is a valid field name
5. Verify that the right side of the `:` is a valid option for said field
6. Verify that at least one `contact` field has been parsed

For contact fields specifically the [validation in the Go parser I wrote](https://github.com/tomnomnom/securitytxt/blob/master/validators.go#L31-L33) is:

```go
func validContact(c string) bool {
	return validEmail(c) || validURI(c) || validPhone(c)
}
```

Where `validEmail()`, `validURI()` and `validPhone()` each are no more than a couple of lines of code.

It would be slightly more complicated if your preference is to tokenise the file with a traditional byte-by-byte approach, but not unreasonably so. I 

Validating that there is at least one `contact` field is also [fairly simple](https://github.com/tomnomnom/securitytxt/blob/master/parse.go#L68-L70):

```go
if len(f.Contact()) < 1 {
	f.addError(fmt.Errorf("does not contain at least one contact field"))
}
```
## Line endings
> 7. The Draft RFC says every line must end with a "\n".
That becomes a problem when Windows users use \r\n.

This is something did change in the grammar / ABNF as a result of writing examples parsers. Initially a single `\n` was required, but I was very keen that the line endings allow for both `\n` and `\r\n` and so End Of Line is defined to be:

```
eol = *WSP [CR] LF
```

That is: any amount of whitespace (as defined in [rfc5234](https://tools.ietf.org/html/rfc5234)), an optional carriage return (`\r`) character and then a line feed character (`\n`).

This scheme is easily handled by the algorithm listed above in the first two steps:

1. Split the file by `\n`
2. Trim remaining whitespace from the ends of the lines

Most languages' standard libraries have facilities to perform both of these steps easily. Again, in a byte-by-byte tokeniser the problem become more difficult, but I don't really see a benefit to writing the parser using that approach because the alternative is that much easier.

I hope I've alleviated some of your concerns, but feel free to press for more details where you think it's appropriate to do so.

**Comment by hackerfactor** [comment]
@tomnomnom:  I don't have too much time to write a detailed reply today. (Apologies for the brevity.)

What about ALWAYS requiring a URL for the contact field?
Contact: tel://+1-202-555-1212x1234
Contact: mailto://security@example.com
Contact: http://security.example.com/bounty.aspx

The various schemes (tel, mailto, http) are all well-defined already.

**Comment by hackerfactor** [comment]
@EdOverflow:
>>  And nothing stops me from adding in my own custom field, like a massive video (DVD-HD, of course) that shows how to submit a bug.
>
> What solution would you propose to this potential issue?

Require every entry to be in the format:
  field ':' url

For example:
  Contact: tel://+1-202-555-1212
  Contact: fax://+1-202-555-1213
  Contact: mailto://security@example.com?subject=Vulnerability+Report
  Encryption: https://example.com/php-key.txt
  Disclosure: https://security.example.com/security.html
  Logo: data:image/png;base64,iVBOR...
  Signature-Key: https://example.com/pgp-key.dat
  Signature: pgp-sig:010203040506...

Also, define a maximum line length. (512 characters should be plenty for a URL. Anything longer and it should point to an external resource.)

**Comment by tomnomnom** [comment]
>  I don't have too much time to write a detailed reply today. (Apologies for the brevity.)

@hackerfactor: no need to apologise :)

> What about ALWAYS requiring a URL for the contact field?

This is actually something we talked about a fair bit. 

The URI schemes you mentioned (`tel:`, `mailto:` etc) are valid values for the `contact` field according to the draft, as they meet the requirements laid out in [https://tools.ietf.org/html/rfc3986](rfc3986), so people can feel free to use them if they want.

One of the goals of the project was to reduce the friction of adoption - even where it makes parsing slightly harder. In the interests of pragmatism we decided to also accept what are essentially email addresses and phone numbers without the scheme part of the URI; to make it easier for people to hand-write their security.txt file, and to make it read better to humans.

In the first draft of the ABNF I wrote, it was essentially as you have suggested - because I had similar fears around the difficulty of parsing the contact fields. After writing a couple of parsers however, I realised the additional burden of supporting scheme-less phone numbers and email addresses was not as great as I had anticipated.

**Comment by hackerfactor** [comment]
@tomnomnom While distinguishing a phone number from an email address or url are pretty simple examples, consider fax vs sms vs voice phone.  They all use phone numbers.  Requiring a URL distinguishes the different types of phone systems.  (You don't want to accidentally call a fax number unless you enjoy getting blasted in the ear by high pitched sounds.)

And today, email is a very common option. However, email is getting phased out. Many companies want to be contacted via twitter, facebook, or other social media.  Or in the case of this rfc review: email failed (required an opt-in to an unspecified mailing list), so my only option was this github forum.  The URL permits specifying alternate contact methods (for flexibility):
Contact: twitter:hackerfactor
Contact: https://twitter.com/hackerfactor
Contact: https://github.com/EdOverflow/security-txt
Now it has maximum flexibility and doesn't require special-case parsers.  You still need to know how to handle the scheme, but you don't need to know how to parse the field.

**Comment by EdOverflow** [comment]
@nickshanks, we already do that in the latest draft: https://tools.ietf.org/html/draft-foudil-securitytxt-03#section-3.3. I completely agree with you.
