### ISSUE TITLE
Consider adding support for ".well-known" protocol / RFC 5785

### ISSUE THREAD

**Issue by nightwatchcyber** [securitytxt/security-txt#3]
The ".well-known" standard or RFC 5785 is the proposed way to websites to store things like "robots.txt":
https://tools.ietf.org/html/rfc5785

It is currently used for the ACME protocol used by LetsEncrypt for SSL domain verification:
https://tools.ietf.org/html/draft-ietf-acme-acme-07#section-9.2

Other protocols out there that use "/.well-known":
https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml

Please consider supporting this for "security.txt" as well

**Comment by april** [comment]
Please, this is much better than having a document at the top level and keeps your hierarchy from being too cluttered.

**Comment by EdOverflow** [comment]
Thank you for the suggestion. Lots of people have been suggesting this to me, so I will definitely look into this.

**Comment by EdOverflow** [comment]
@nightwatchcyber & @april: I have decided that I will be adding support for the ".well-known" protocol. :slightly_smiling_face:

**Comment by EdOverflow** [comment]
I have added this to the README.md: https://github.com/EdOverflow/security-txt#how-it-works. Thank you @nightwatchcyber & @april.

**Comment by nightwatchcyber** [comment]
You may want to register with IANA:

https://www.ietf.org/assignments/well-known-uris/well-known-uris.xml

This can be done part of the IETF draft

**Comment by EdOverflow** [comment]
@nightwatchcyber & @april: After a very long and heated debate with some other people, I have decided to go with the original idea of having security.txt in the root directory. The main reason for not using `/.well-known/` was the fact that it is not widely used. Most people I talked to had never even heard of it in the first place. This is surprising since the RFC was published in April 2010.

I apologise for this last-minute decision. Hopefully, this will not cause too much trouble.

**Comment by EdOverflow** [comment]
This issue is now back open for discussion.

**Comment by EdOverflow** [comment]
The new draft that I have not published yet places security.txt under the /.well-known/ path, but I would still like to discuss this further because of this poll: https://twitter.com/EdOverflow/status/916638593027919873.

![image](https://user-images.githubusercontent.com/18099289/31316809-43224990-ac35-11e7-8cf0-dc7781848dae.png)

**Comment by x3ro** [comment]
Hi @EdOverflow. Thanks for getting this started project started!

On topic: Why is it relevant whether or not people are well-aware of `.well-known`? You'd have to learn/know about the existence of `security.txt` in order to look at it, so it wouldn't matter what the exact path of it is, right? While learning about `security.txt` people would then automatically also learn about `.well-known` if they weren't aware of it before.

Or to put it differently: what would be the advantage of putting `security.txt` in the root directory over putting it in a standard location defined by an RFC?

**Comment by EdOverflow** [comment]
Hi @x3ro,

> Why is it relevant whether or not people are well-aware of .well-known?

I have actually changed my mind about that since the [last decision](https://github.com/securitytxt/security-txt/issues/3#issuecomment-328464635) was made.

> what would be the advantage of putting security.txt in the root directory over putting it in a standard location defined by an RFC?

One advantage would be that this would make security.txt comply with robots.txt. Something that is already fairly familiar with most people and companies.

> In the end, if you want to publish this as an RFC you should also consider that it'll need to pass through all IETF scrutiny, and I find it hard to believe that the poll would have the same outcome there.

I am waiting to hear back from the IETF board about the location of the file. Maybe they can help me come to a definitive conclusion.

**Comment by EdOverflow** [comment]
@x3ro, @april & @nightwatchcyber: I have finally come to a conclusion. security.txt will be placed under the `/.well-known/` path. The Google VRP team have convinced me. This will be made clear in the next version of the draft. Thank you very much for the constructive feedback and help.

**Comment by april** [comment]
robots.txt was created back in 1994, back when we thought that using
unstructured text files and putting them in the root directory was a
good idea.

**Comment by austinheap** [comment]
+1 good call on using `/.well-known/`

> robots.txt was created back in 1994, back when we thought that using
> unstructured text files and putting them in the root directory was a
> good idea.

Couldn't agree more! No reason to bring along poorly thought out decisions from 20~ years ago.

**Comment by nightwatchcyber** [comment]
@EdOverflow - considering how successful the ".well-known" approach worked in regards to the ACME protocol used by LetsEncrypt, it will probably work well for this as well. Thanks.
