### ISSUE TITLE
warrant canary url field

### ISSUE THREAD

**Issue by jefforulez** [securitytxt/security-txt#38]
it would be great if there was a field for specifying an organization's warrant canary url.

**Comment by hackerfactor** [comment]
My initial thought was that this is a really cute idea. But:
1. It should be optional.
2. It might get complicated since different countries have different types of warrants.

WarrantCanary: List of warrants that we have never received.
WarrantCanary: DMCA, Patriot Act, US NSL, US FISA, UK NSL, AU NSL, ...

The problem is that there are lots of different types of warrants, and they are not just limited to the United States. Moreover, canaries may not be enforceable; as Moxie Marlinspike is quoted on Wikipedia (https://en.wikipedia.org/wiki/Warrant_canary): removing, updating, or failing to update a warrant canary would likely be no difference than posting that you have received the letter.  Until it is resolved in the legal world, the security.txt specs should not be taking on a legal nightmare.

I think warrant canaries should be their own RFC and not shoehorned into security.txt.

**Comment by austinheap** [comment]
Love the idea, agree it should be optional, but I agree with @hackerfactor that defining it into a structure that works for as many parties as possible might be difficult if not impossible.

**Comment by jefforulez** [comment]
thanks for the feedback @hackerfactor @austinheap!

just to be clear, i'm only suggesting having a field for a **URL** that points to an organization's canary, not any specific information about the canary itself.   

this would be informational to help researchers or professionals know where a canary lives.

for example, our canary url is https://www.firstlook.media/canary, but finding that url isn't 100 percent straight-forward, especially if you're coming from one of branded sites such as theintercept.com or thenib.com.

a diff to the RFC would look something like this:  

```
--- ./draft-foudil-securitytxt-00.txt	2017-10-09 16:07:07.000000000 -0400
+++ ./draft-foudil-securitytxt-01.txt	2017-10-09 16:07:11.000000000 -0400
@@ -210,6 +210,8 @@
 
    acknowledgement-field  = "Acknowledgement" fs SP uri
 
+   warrant-canary-field   = "Warrant Canary" fs SP uri
+
 4.  Security Considerations
 
    Companies creating security.txt files will need to take several
```

download: [draft-foudil-securitytxt-00.txt.diff.txt](https://github.com/securitytxt/security-txt/files/1369695/draft-foudil-securitytxt-00.txt.diff.txt)

**Comment by hackerfactor** [comment]
Thanks for the explanation.

With your explanation, I approve of the usage.  I'm just not sure about whether it belongs in security.txt.

My hesitation: Other fields in security.txt are explicitly security related. They include directions for contacting the security department, URLs for reporting security issues, etc. In contrast, a warrant canary is strictly a legal issue and not a technical/security issue.

**Comment by austinheap** [comment]
I agree with @hackerfactor -- full support of a `Canary` directive given that it points to a URL.

Re: the hesitations @hackerfactor mentioned -- I could make the argument both ways. The origination of warrant canaries is in direct response to secret subpoenas or national _security_ letters. I think it's fair to include it in `security.txt` because the security of an organization could be deemed compromised if they're subject to extra-ordinary legal demands. That said, I agree it's a legal issue, but it's a legal issue with potential security implications.

On the flip side, warrant canaries have had a rough track record, like with [Canary Watch](https://en.wikipedia.org/wiki/Warrant_canary#Canary_Watch):

>  The Electronic Frontier Foundation also noted that "due to the fact that canaries are non-standard makes it difficult to automatically monitor them for changes or takedowns".

**Comment by nightwatchcyber** [comment]
I would add that if #34 is implemented in an extensible fashion, this can be done as an optional field

**Comment by nightwatchcyber** [comment]
Would this be covered by #53  - Policy field? A canary can be included as part of the policy page?

**Comment by EdOverflow** [comment]
@nightwatchcyber, yes, I agree with you. I am closing this issue now.
