### ISSUE TITLE
Awkward sentence

### ISSUE THREAD

**Issue by strugee** [securitytxt/security-txt#86]
Section 2.3 contains this sentence:

> While URIs already include the ability to have both email address and phone numbers via "mailto" and "tel" prefixes, allowing this information to be listed without a prefix is intended for ease of use and readability.

I personally found this confusing. How about instead:

> While URIs already include the ability to have both email address and phone numbers via "mailto" and "tel" prefixes, this information can be listed without a prefix in security.txt documents to improve ease of use and readability.

**Comment by strugee** [comment]
I should add that I'm happy to prepare a PR for this change, just wasn't sure what branch to send it to

**Comment by EdOverflow** [comment]
Hi @strugee,

Thank you for contributing to the _security.txt_ project. As far as I can tell this is not an issue anymore since we completely removed that passage in [security-03](https://github.com/securitytxt/security-txt/pull/81). The previous issue discussing this can be found here: https://github.com/securitytxt/security-txt/issues/62.
